---
- name: Get helm release info
  become: false
  uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
    headers:
      Accept: 'application/vnd.github.v3+json'
    return_content: yes
  register: helm_release_info
  changed_when: false

- name: Get Available Helm Version
  become: false
  set_fact:
    helm_version: "{{ helm_release_info.json.tag_name }}"
  changed_when: false

- name: Set Helm Download URL
  become: false
  set_fact:
    helm_download_url: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-amd64.tar.gz
  changed_when: false

